algo_config:
  horizon: 10
  r_mpc:
    - 0.1
  q_mpc:
    - 10
    - 1
    - 1
    - 1
  # gp_model_path: ./baselines/experiment_results/experiment_results/gp_mpc_cartpole/no_disturbances
  gp_model_path: null
  train_iterations: 150
  validation_iterations: 1
  optimization_iterations:
    - 2000
    - 2000
    - 2000
    - 2000
  learning_rate:
    - 0.01
    - 0.01
    - 0.01
    - 0.01
  normalize_training_data: false
  use_gpu: false
  inertial_prop: null
  prior_param_coeff: 1.5
  prob: 0.955
  initial_rollout_std: 0.001
  warmstart: true
  gp_approx: 'mean_eq'
  sparse_gp: false
  plot: True
  online_learning: false
  # additional_constraints:
  #   - constraint_form: linear_constraint
  #     A:
  #       - [ -1.0, 0.0, 0.0, 0.0 ]
  #     b:
  #       - 1.1
  #     constrained_variable: state
  input_mask: 
   - 0
   - 1
   - 2
   - 3
   - 4
  output_mask: 
   - 0 
   - 1
   - 2
   - 3
task_config:
  ctrl_freq: 10
  pyb_freq: 240
  info_in_reset: True
  normalized_rl_action_space: False
  constraints:
    - constraint_form: default_constraint
      constrained_variable: input
    - constraint_form: abs_bound
      bound: 1
      constrained_variable: state
      active_dims: 0
  #   - constraint_form: abs_bound
  #     bound: 0.5
  #     constrained_variable: state
  #     active_dims: 2 
  #   - constraint_form: default_constraint
  #     constrained_variable: input
  # disturbances: 
  #     dynamics:
  #     - disturbance_func: white_noise
  #       std: 0.1
  done_on_violation: True
  # init_state: 
  #   init_x: 0.7
  #   init_x_dot: 1.0
  #   init_theta: 0.45
  #   init_theta_dot: -0.3

  randomized_init: True
  init_state_randomization_info:
    init_x:
      distrib: 'uniform'
      low: -0.5
      high: 0.5
    init_x_dot:
      distrib: 'uniform'
      low: -0.5
      high: 0.5
    init_theta:
      distrib: 'uniform'
      low: -0.35
      high: 0.35
    init_theta_dot:
      distrib: 'uniform'
      low: -0.15
      high: 0.15
  env_disturbance: 
    variable: dynamics
    scheduler: cyclic
    active_dims: [0,1]
    start: [0.0,0.0]
    sign: [-1,1]
    max: [0, 0.1]
    min: [-0.1,0]
    scale: [1, 1]
    std: [0.01, 0.01]
