algo_config:
  horizon: 10
  r_mpc:
    - 0.1
  q_mpc:
    - 1
    - 1
    - 1
    - 1
  gp_model_path: null
  train_iterations: 800
  validation_iterations: 200
  optimization_iterations:
    - 2000
    - 2000
    - 2000
    - 2000
  learning_rate:
    - 0.01
    - 0.01
    - 0.01
    - 0.01
  normalize_training_data: False
  use_gpu: false
  inertial_prop: null
  prior_param_coeff: 1.5
  prob: 0.955
  initial_rollout_std: 0.005
  warmstart: True
  gp_approx: 'mean_eq'
  sparse_gp: false
  online_learning: False
  output_dir: './trained_gp_model'

task_config:
  ctrl_freq: 10
  pyb_freq: 240
  info_in_reset: True
  done_on_violation: True
  disturbances: null
  constraints:
    - constraint_form: abs_bound
      bound: 0.4
      constrained_variable: state
      active_dims: 0
    - constraint_form: default_constraint
      constrained_variable: input
      upper_bounds: 0.2
  init_state:
    init_x: 0.1
    init_x_dot: -0.5
    init_theta: -0.19
    init_theta_dot: -0.5
  randomized_init: False
  init_state_randomization_info:
    init_x:
      distrib: uniform
      low: -0.05
      high: 0.05
    init_x_dot:
      distrib: uniform
      low: -0.05
      high: 0.05
    init_theta:
      distrib: uniform
      low: -0.05
      high: 0.05
    init_theta_dot:
      distrib: uniform
      low: -0.05
      high: 0.05
