algo_config:
  log_interval: 1000
  save_interval: 1000
  num_checkpoints: 10
  eval_interval: 1000
  eval_save_best: True 
  tensorboard: True
render: true
task_config:
  info_in_reset: True
  normalized_rl_action_space: False
  constraints:
    - constraint_form: abs_bound
      bound: 1
      constrained_variable: state
      active_dims: 0
    - constraint_form: abs_bound
      bound: 0.5
      constrained_variable: state
      active_dims: 2 
  done_on_violation: False
  disturbances: 
    dynamics:
    - disturbance_func: white_noise
      std: 0.0
    action:
    - disturbance_func: white_noise
      std: 0.0
    observation:
    - disturbance_func: white_noise
      std: 0.0