algo_config:
  pretraining: False 
  pretrained: ./baselines/experiment_results/experiment_results/safe_explorer_cartpole/seed222_Apr-05-21-20-53_v0.5.0-96-g475df85
  constraint_slack: 0.15
  log_interval: 1000
  save_interval: 1000
  num_checkpoints: 10
  eval_interval: 1000
  eval_save_best: True 
  tensorboard: True
render: true
task_config:
  info_in_reset: True
  normalized_rl_action_space: False
  constraints:
    - constraint_form: abs_bound
      bound: 1
      constrained_variable: state
      active_dims: 0
    - constraint_form: abs_bound
      bound: 0.5
      constrained_variable: state
      active_dims: 2 
  done_on_violation: False
  # init_state: 
  #   init_x: 0.7
  #   init_x_dot: 1.0
  #   init_theta: 0.45
  #   init_theta_dot: -0.3
  randomized_init: True
  init_state_randomization_info:
    init_x:
      distrib: 'uniform'
      low: -0.5
      high: 0.5
    init_x_dot:
      distrib: 'uniform'
      low: -0.75
      high: 0.75
    init_theta:
      distrib: 'uniform'
      low: -0.5
      high: 0.5
    init_theta_dot:
      distrib: 'uniform'
      low: -0.25
      high: 0.25

