algo_config:
  pretraining: False 
  pretrained: ./baselines/experiment_results/experiment_results/safe_explorer_cartpole/seed222_Apr-11-21-50-59_v0.5.0-102-g29c035f
  constraint_slack: 0.05
  log_interval: 1000
  constraint_hidden_dim: 64
  save_interval: 1000
  num_checkpoints: 10
  eval_interval: 1000
  eval_save_best: True 
  tensorboard: True
render: true
task_config:
  info_in_reset: True
  normalized_rl_action_space: False
  constraints:
    - constraint_form: abs_bound
      bound: 1
      constrained_variable: state
      active_dims: 0
    - constraint_form: abs_bound
      bound: 0.5
      constrained_variable: state
      active_dims: 2 
  done_on_violation: False
  init_state: 
    init_x: 0.45
    init_x_dot: 0.2
    init_theta: 0.2
    init_theta_dot: -0.1
  randomized_init: False
  # init_state_randomization_info:
  #   init_x:
  #     distrib: 'uniform'
  #     low: -0.5
  #     high: 0.5
  #   init_x_dot:
  #     distrib: 'uniform'
  #     low: -0.5
  #     high: 0.5
  #   init_theta:
  #     distrib: 'uniform'
  #     low: -0.35
  #     high: 0.35
  #   init_theta_dot:
  #     distrib: 'uniform'
  #     low: -0.15
  #     high: 0.15
  disturbances: 
    dynamics:
    - disturbance_func: white_noise
      std: 0.10
  # env_disturbance: 
  #   variable: dynamics
  #   scheduler: cyclic
  #   active_dims: [0,1]
  #   start: [1,0]
  #   sign: [-1,1]
  #   max: [1, 1]
  #   min: [0,-1]
  #   scale: [0.1, 0.1]
  #   std: [0.01, 0.01]

