algo: ppo
algo_config:
  actor_lr: 0.0003
  clip_obs: 10.0
  clip_param: 0.2
  clip_reward: 10.0
  critic_lr: 0.001
  deque_size: 10
  entropy_coef: 0.01
  eval_batch_size: 10
  eval_interval: 1000
  eval_save_best: true
  gae_lambda: 0.95
  gamma: 0.99
  hidden_dim: 64
  log_interval: 1000
  max_env_steps: 1000000
  max_grad_norm: 0.5
  mini_batch_size: 64
  norm_obs: false
  norm_reward: false
  num_checkpoints: 10
  num_workers: 1
  opt_epochs: 10
  rollout_batch_size: 4
  rollout_steps: 100
  save_interval: 1000
  target_kl: 0.01
  tensorboard: true
  use_clipped_value: false
  use_gae: false
device: cuda
eval_output_path: test_results.pkl
func: train
output_dir: ./tutorial_models/tutorial_results/ppo/seed222_Feb-04-10-31-47_v0.5.0-54-g5fb9629
overrides:
- ./tutorial_configs/tutorial_ppo_cartpole.yaml
render: false
restore: null
seed: 222
set_test_seed: false
tag: tutorial_results/ppo
task: cartpole
task_config:
  adversary_disturbance: null
  adversary_disturbance_offset: 0.0
  adversary_disturbance_scale: 0.01
  constraint_penalty: -1
  constraints:
  - active_dims: 0
    bound: 0.4
    constrained_variable: state
    constraint_form: abs_bound
  cost: rl_reward
  ctrl_freq: 50
  disturbances: null
  done_on_out_of_bound: true
  done_on_violation: true
  episode_len_sec: 5
  gui: false
  inertial_prop: null
  inertial_prop_randomization_info: null
  info_in_reset: true
  init_state: null
  init_state_randomization_info: null
  normalized_rl_action_space: false
  obs_wrap_angle: false
  pyb_freq: 50
  randomized_inertial_prop: false
  randomized_init: true
  rew_act_weight: 0.0001
  rew_exponential: true
  rew_state_weight: 1.0
  task: stabilization
  task_info: null
  use_constraint_penalty: false
  verbose: false
thread: 1
use_adv: false
verbose: false
