algo_config:
  max_num_steps: 500
  use_safe_input: True
  use_learned_model: True

  soft_constrained: True
  slack_weight: 10000.0 # 0.0
  slack_tolerance: 1.0E-3 # 0.0

  hidden_dims: [256, 256]
  learning_rate: 0.001

  num_episodes: 1
  max_buffer_size: 1.0E+6
  train_batch_size: 64
  train_iterations: 200






task_config:
  ctrl_freq: 100
  pyb_freq: 1000

  # randomization
  inertial_prop: null
  randomized_inertial_prop: False
  inertial_prop_randomization_info: null

  #prior_prop: null
  prior_prop:
    pole_length: 0.4
    pole_mass: 0.12
    cart_mass: 0.8

  randomized_init: False
  init_state_randomization_info: null

  # state initialization
  init_state:
    init_x: 0.55
    init_x_dot: 0.5
    init_theta: 0.30
    init_theta_dot: -0.1

  # constraints
  # constraints:
  # - constraint_form: default_constraint
  #   constrained_variable: state
  # - constraint_form: default_constraint
  #   constrained_variable: input
  #   upper_bounds:
  #     - 8.0
  #   lower_bounds:
  #     - -8.0
  constraints:
  - constraint_form: bounded_constraint
    upper_bounds:
      - 1
    lower_bounds:
      - -1
    constrained_variable: state
    active_dims: 0
  - constraint_form: bounded_constraint
    upper_bounds: 
      - 0.5
    lower_bounds: 
      - -0.5
    constrained_variable: state
    active_dims: 2 
